config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-wheat-zebra.sh
        container: qc.acc_tasty-alizarin-ocelot
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-platinum-gorilla.sh
        container: qc.doc_sleazy-tomato-hyena
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-linen-frog.sh
        container: qc.doc_stuffy-cyan-serval
      github.com/PalomoIFCA/testnotebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-scarlet-butterfly.sh
        container: qc.doc_beady-magenta-walrus
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-coral-squid.sh
        container: qc.lic_squeaky-periwinkle-falcon
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-magenta-caterpillar.sh
        container: qc.ver_slaphappy-heliotrope-dugong
timeout: 5400
