config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-chocolate-bombay.sh
        container: qc.acc_droopy-blue-fly
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-plum-donkey.sh
        container: qc.doc_snappy-russet-camel
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ruby-eagle.sh
        container: qc.doc_tasty-bronze-okapi
      github.com/PalomoIFCA/testnotebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ochre-gharial.sh
        container: qc.doc_muggy-fuchsia-shrimp
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-grey-affenpinscher.sh
        container: qc.lic_blurry-puce-serval
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-denim-pig.sh
        container: qc.ver_gimpy-zucchini-indri
timeout: 5400
