config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-setter.sh
        container: qc.acc_squirrely-indigo-moorhen
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-jade-lion.sh
        container: qc.doc_snippy-ultramarine-tang
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-zucchini-boar.sh
        container: qc.doc_cheeky-ochre-cat
      github.com/PalomoIFCA/testnotebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-razzmatazz-camel.sh
        container: qc.doc_nerdy-cardinal-cichlid
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-turquoise-emu.sh
        container: qc.lic_greasy-platinum-lynx
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-aqua-dodo.sh
        container: qc.ver_foggy-jade-worm
timeout: 5400
