config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-mustard-numbat.sh
        container: qc.acc_cozy-aqua-buzzard
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sangria-ibis.sh
        container: qc.doc_cloudy-wisteria-whale
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-emerald-dodo.sh
        container: qc.doc_surly-ecru-opossum
      github.com/PalomoIFCA/testnotebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-ivory-millipede.sh
        container: qc.doc_baggy-zucchini-mongoose
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cerise-shark.sh
        container: qc.lic_droopy-saffron-wallaby
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-violet-anteater.sh
        container: qc.ver_scanty-turquoise-olm
timeout: 5400
