config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-tomato-abyssinian.sh
        container: qc.acc_bluesy-ultramarine-hyrax
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-heliotrope-warthog.sh
        container: qc.doc_blurry-saffron-ostrich
      github.com/PalomoIFCA/testnotebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-wisteria-worm.sh
        container: qc.doc_gloppy-gold-wallaby
      github.com/PalomoIFCA/testnotebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ochre-ray.sh
        container: qc.doc_lousy-thistle-rottweiler
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-teal-cuscus.sh
        container: qc.lic_snazzy-persimmon-hedgehog
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cinnamon-cattle.sh
        container: qc.ver_flimsy-razzmatazz-gibbon
timeout: 5400
